# Generated by Django 5.1 on 2024-12-31 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=50, unique=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("standard", "standard"), ("urgent", "urgent")],
                        default="standard",
                        max_length=10,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("zr", "Zirconium"),
                            ("pmma", "PMMA"),
                            ("emax", "EMAX"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "shade",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="shade"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=32)),
                ("display_name", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NextStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signal", models.CharField(max_length=32)),
                ("display_name", models.CharField(max_length=64)),
                (
                    "current",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_state",
                        to="core.stage",
                    ),
                ),
                (
                    "next",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_state",
                        to="core.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Next Stage",
                "verbose_name_plural": "Next Stages",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="CaseStageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_logs",
                        to="core.case",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_logs",
                        to="core.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Case Stage Log",
                "verbose_name_plural": "Case Stage Logs",
                "ordering": ["start_time"],
            },
        ),
        migrations.AddField(
            model_name="case",
            name="current_stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.stage"
            ),
        ),
    ]
