# Generated by Django 5.1 on 2025-06-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="stage_group",
            field=models.CharField(
                db_index=True, max_length=32, null=True, unique=True
            ),
        ),
    ]
