# Generated by Django 5.1 on 2025-02-07 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_returnreason_alter_case_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nextstage",
            options={
                "ordering": ["display_name"],
                "verbose_name": "Next State",
                "verbose_name_plural": "Next States",
            },
        ),
        migrations.AlterModelOptions(
            name="stage",
            options={
                "ordering": ["name"],
                "verbose_name": "State",
                "verbose_name_plural": "States",
            },
        ),
        migrations.RenameField(
            model_name="stage",
            old_name="description",
            new_name="note",
        ),
        migrations.AddField(
            model_name="case",
            name="next_state_intent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.nextstage",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="case_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="material",
            field=models.CharField(
                blank=True,
                choices=[("zr", "Zirconium"), ("pmma", "PMMA"), ("emax", "EMAX")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="casestagelog",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stage_logs_case",
                to="core.case",
            ),
        ),
        migrations.AlterField(
            model_name="casestagelog",
            name="stage",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stage_logs_stage",
                to="core.stage",
            ),
        ),
    ]
