# Generated by Django 5.1 on 2025-02-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_nextstage_options_alter_stage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="priority",
            field=models.CharField(
                choices=[("standard", "STANDARD"), ("urgent", "URGENT")],
                default="standard",
                max_length=10,
            ),
        ),
    ]
