# Generated by Django 5.1 on 2025-02-08 11:45

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customuser"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", core.models.CustomUserManager()),
            ],
        ),
    ]
