# Generated by Django 5.1 on 2025-02-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "view_case_processing_all_cases",
                        "Can view all cases for processing",
                    ),
                    ("manage_case", "Can manage a specific case"),
                    ("archive_cases", "Can archive a specific case"),
                    ("return_cases", "Can return a specific case"),
                ],
                "verbose_name": "Case",
                "verbose_name_plural": "Cases",
            },
        ),
    ]
