# Generated by Django 5.1 on 2025-02-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnreason",
            name="reason",
            field=models.CharField(
                choices=[
                    ("defect", "Defect"),
                    ("wrong_design", "Wrong Design"),
                    ("chip", "Chip"),
                    ("color_mismatch", "Color Mismatch"),
                    ("other", "Other (Specify Below)"),
                ],
                default="defect",
                max_length=32,
                unique=True,
            ),
        ),
    ]
