# Generated by Django 5.1 on 2025-03-04 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_returnreason_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="barcode",
            field=models.CharField(
                db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="barcode",
            field=models.CharField(
                db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        db_index=True, max_length=50, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Связь с пользователем системы (опционально)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AddField(
            model_name="case",
            name="last_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_updated",
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="casestagelog",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.employee",
            ),
        ),
    ]
